- src/dialogs/NewDialog.cpp
- src/dialogs/dropshadowdialog.cpp
- src/dialogs/gradientdialog.cpp
- src/dialogs/huedialog.cpp
- src/dialogs/textdialog.cpp
- src/dialogs/transparentdialog.cpp
Fixes: https://github.com/PhotoFlare/photoflare/issues/37
Let me know if there are related settings that should also be removed
> Rm dialog read/write

- PhotoFlare.pro
Make library paths more portable and for newer version of graphicsmagick
> Fix mac build lib paths

- .gitignore
- languages/diffing_tool.py
Tool is built with python2.7.x
TODO:
expand to take args on what lang to target or process all.
print to file rather than to terminal?
> Add initial version of diffing-tool

- src/dialogs/NewDialog.cpp
- src/dialogs/NewDialog.h
- src/mainwindow.cpp
If you are working on a new feature please choose one from issues with the enhancement label. Otherwise your feature may or may not be accepted into master.
Give a brief description of the feature/bug fix and if the solution differs from the suggested issue solution.
Tag the issue number that your pull request relates to.
Provide some information on your test results. Eg. Before and after your fix.
Only required for fixes or features that involve a visual element.
> Newdialog mode fix

- src/mainwindow.cpp
- src/tools/PointerTool.cpp
- src/tools/PointerTool.h
Fixes: https://github.com/PhotoFlare/photoflare/issues/54
Maybe not fully done, but you probably want to merge to unblock?
Todo:
* Disable menu items that cannot be completed
* Should right click menu be openable with no file open?
> Add more items to right click menu

- PhotoFlare.pro
This commit fix the problem of missing icon in the applications menu.
> Install more files with INSTALL target

- PhotoFlare.pro
Workaround shamefully copied from [here](https://github.com/wereturtle/ghostwriter/commit/050c7c22).
> Fix Qt version detection. Fixes #36

- PhotoFlare.pro
Successfully applied in [Debian](https://salsa.debian.org/debian-phototools-team/photoflare/blob/master/debian/patches/ftbfs_hurd.patch)
> Fix FTBFS on Hurd

- PhotoFlare.pro
- src/main.cpp
- src/mainwindow.cpp
- src/mainwindow.h
- src/managers/FilterManager.cpp
- src/workers/filterworker.cpp
- src/workers/filterworkermp.cpp
- src/workers/filterworkermp.h
Use OpenMp for certain filters that can use images split into segments. (without any artifacts after filter use)
For use with libgraphicsmagick.
> Openmp Hybrid for filters

- Photoflare.pro
- languages/zh_CN.ts
- src/dialogs/aboutdialog.cpp
> Translation of Simplified Chinese (zh_CN)

- languages/cs.ts
only a small refresh of the Czech translation. if you find it useful, use it :-)
> Update czech language

- src/dialogs/batchdialog.cpp
> Missing Translations "tr()"

- src/mainwindow.ui
I found the solution to the problem in the window icon...
Test it...
:+1:
> fixed window icon

- src/main.cpp
Translations not loading in master after installation due appropriate file not found (not "for installers", but "for local builders").
> Fix check of translation file

- installers/deb/DEBIAN/usr/share/applications/photoflare.desktop
Update desktop entry with Russian translation of Comment and GenericName.
> Add Russian language to desktop entry

- languages/es.ts
Spanish translation for Photoflare.
> Add spanish translation

- languages/es.ts
Fix a few minor mistakes in Spanish translation.
> Fix a few minor mistakes in Spanish translation.

- installers/deb/DEBIAN/usr/share/applications/photoflare.desktop
partially fixes PhotoFlare/photoflare#134
> Fix missing taskbar icon on kde plasma

- languages/nl.ts
> Updated Dutch translation

- .github/README.md
- src/dialogs/aboutdialog.cpp
Add Turkish as a supported language.
Add sabriunal to the about dialog as a translator.
> Update readme and about dialog

- languages/es.ts
Fix a few Spanish translation strings.
> Update spanish translation

- languages/ja.ts
This is to provide more Japanese translations.
> More Japanese translations

- languages/ja.ts
Some more translations in Japanese
Tested locally by contributor (me)
> Update Japnaese translation

- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/tools/PointerTool.cpp
- src/tools/PointerTool.h
This is to add "Fill Rectangle" function, mentioned as 'Fill' in #267 
This is not connected to the SelectionMode Fill yet, there may be some way to do so.
It is working in local build on my side.
> add "Fill Rectangle"
